 
package view;

import Model.DeleteData;
import Model.InsertData;
import Model.ShowData;
import Model.UpdateData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Model.Classes;

public class FrmProd extends javax.swing.JFrame {

    private int xMouse, yMouse;
    
    private List<String> nombreColumnas = new ArrayList<>();
    private List<String> interrogaciones = new ArrayList<>();
    
    private String nombreTabla = "product";
    private List<String> column = new ArrayList<>();
    private List<String> campos = new ArrayList<>();
    private String id;
    
    private String buscar = "";
    private String campoBuscar = "description";
    
    public FrmProd() {
        initComponents();
        
        column.add("Id");
        column.add("Descripción Producto");
        column.add("id Marca");
        column.add("id Medida");
        column.add("id Sección");
        column.add("id Categoría");
        
        nombreColumnas.add("description");
        nombreColumnas.add("id_brand");
        nombreColumnas.add("id_measure");
        nombreColumnas.add("id_section");
        nombreColumnas.add("id_cat");
        
        Model.AddImage.SetImageLabel(btnSalir, "src/images/atras.png");
        
        this.setLocationRelativeTo(null);
        
        showData();
        
        ShowData.getShowData().rellenarComboBox("brand_prod", "id", cmbBrand);
        ShowData.getShowData().rellenarComboBox("measure_prod", "id", cmbMeasures);
        ShowData.getShowData().rellenarComboBox("section_prod", "id", cmbSection);
        ShowData.getShowData().rellenarComboBox("cat_prod", "id", cmbCat);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBlue = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        cmbBrand = new javax.swing.JComboBox<>();
        lblMeasures = new javax.swing.JLabel();
        cmbMeasures = new javax.swing.JComboBox<>();
        lblSection = new javax.swing.JLabel();
        cmbSection = new javax.swing.JComboBox<>();
        lblCat = new javax.swing.JLabel();
        cmbCat = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        fldBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1442, 625));
        setMinimumSize(new java.awt.Dimension(1442, 625));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBlue.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 630));

        btnGuardar.setBackground(new java.awt.Color(102, 255, 51));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 170, 80));

        btnModificar.setBackground(new java.awt.Color(255, 255, 51));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Modificar");

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(31, 31, 31))
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 170, 80));

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 190, 100));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(23, 23, 23))
        );

        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 170, 80));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1090, 410));

        jLabel1.setFont(new java.awt.Font("Roboto Cn", 1, 48)); // NOI18N
        jLabel1.setText("PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 30));

        lblName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblName.setText("Descripción del Producto");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 60, -1, 30));

        fldName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNameActionPerformed(evt);
            }
        });
        getContentPane().add(fldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, 260, 40));

        lblBrand.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblBrand.setText("Id Marca:");
        getContentPane().add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 130, -1, 30));

        cmbBrand.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cmbBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(cmbBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 160, 260, 40));

        lblMeasures.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblMeasures.setText("Id Medida:");
        getContentPane().add(lblMeasures, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 200, -1, 30));

        cmbMeasures.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        getContentPane().add(cmbMeasures, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, 260, 40));

        lblSection.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSection.setText("Id Sección:");
        getContentPane().add(lblSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 270, -1, 30));

        cmbSection.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        getContentPane().add(cmbSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 300, 260, 40));

        lblCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCat.setText("Id Categoría:");
        getContentPane().add(lblCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 340, -1, 30));

        cmbCat.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        getContentPane().add(cmbCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 370, 260, 40));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setText("Buscar por producto:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, -1, -1));

        fldBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldBuscarActionPerformed(evt);
            }
        });
        fldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fldBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(fldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 210, 30));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("BUSCAR");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        addCamps();

        int op = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos registrados?", "Confirme los datos registrados",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE); //preguntarle si quiere guardar
        if(op == 0)
        {
            InsertData.getInsertData().insertarDatos(nombreTabla, interrogaciones, column, nombreColumnas, campos); //insertar datos
            clear();
            showData();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        addCamps();
        UpdateData.getUpdateData().actualizarDatos(nombreTabla, nombreColumnas, campos, "id", id);
        clear();
        showData();
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        Classes.ExecuteMenuOptions();
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        //Eliminar datos

        int op = JOptionPane.showConfirmDialog(null, "¿Desea eliminar los datos?", "Confirme si desea eliminar",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(op == 0)
        {
            DeleteData.getDeleteData().eliminarTablaCod(nombreTabla, "id", id);
            clear();
            showData();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); //Guardar eje x y eje y
    }//GEN-LAST:event_headerMousePressed

    private void fldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if(fila == -1 ) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún dato");
        }
        else
        {
            id = jTable1.getValueAt(fila, 0).toString();
            String name = (String)jTable1.getValueAt(fila, 1).toString();
            String brand = (String)jTable1.getValueAt(fila, 2).toString();
            String measures = (String)jTable1.getValueAt(fila, 3).toString();
            String section = (String)jTable1.getValueAt(fila, 4).toString();
            String cat = (String)jTable1.getValueAt(fila, 5).toString();
            
            fldName.setText(name);
            cmbBrand.setSelectedItem(brand);
            cmbMeasures.setSelectedItem(measures);
            cmbSection.setSelectedItem(section);
            cmbCat.setSelectedItem(cat);
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void fldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldBuscarActionPerformed

    }//GEN-LAST:event_fldBuscarActionPerformed

    private void fldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldBuscarKeyReleased
        if(fldBuscar.getText().trim().equals("")){
            showData();
        }
    }//GEN-LAST:event_fldBuscarKeyReleased

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        buscar = fldBuscar.getText();

        showData();
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProd().setVisible(true);
            }
        });
    }
    
      private void addCamps(){
          
        campos.add(fldName.getText());
        campos.add((String)cmbBrand.getSelectedItem());
        campos.add((String)cmbMeasures.getSelectedItem());
        campos.add((String)cmbSection.getSelectedItem());
        campos.add((String)cmbCat.getSelectedItem());
        
    }
    
    private void clear(){
        fldName.setText(null);
        cmbBrand.setSelectedItem(null);
        cmbMeasures.setSelectedItem(null);
        cmbSection.setSelectedItem(null);
        cmbCat.setSelectedItem(null);
    }
    
    private void showData() {
        ShowData.getShowData().mostrarDatos(nombreTabla, jTable1, 6, column, buscar, campoBuscar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JComboBox<String> cmbBrand;
    private javax.swing.JComboBox<String> cmbCat;
    private javax.swing.JComboBox<String> cmbMeasures;
    private javax.swing.JComboBox<String> cmbSection;
    private javax.swing.JTextField fldBuscar;
    private javax.swing.JTextField fldName;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblMeasures;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSection;
    // End of variables declaration//GEN-END:variables
}
