
package view;

import Model.DeleteData;
import Model.InsertData;
import Model.ShowData;
import Model.UpdateData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Model.Classes;

public class FrmSales extends javax.swing.JFrame {


    private int xMouse, yMouse;
    
    private List<String> nombreColumnas = new ArrayList<>();
    private List<String> interrogaciones = new ArrayList<>();
    
    private String nombreTabla = "sales";
    private List<String> column = new ArrayList<>();
    private List<String> campos = new ArrayList<>();
    private String id;
    
    private String buscar = "";
    private String campoBuscar = "id";
    
    
    public FrmSales() {
        initComponents();
        
        column.add("Id");
        column.add("Cantidad");
        column.add("Precio");
        column.add("Fecha");
        column.add("id Producto");
        column.add("id User");
        column.add("id Cliente");
        column.add("id Forma Pago");
        
        nombreColumnas.add("amount");
        nombreColumnas.add("price");
        nombreColumnas.add("date");
        nombreColumnas.add("id_product");
        nombreColumnas.add("id_user");
        nombreColumnas.add("id_client");
        nombreColumnas.add("payment");
        
        Model.AddImage.SetImageLabel(btnSalir, "src/images/atras.png");
        
        this.setLocationRelativeTo(null);
        
        showData();
        
        ShowData.getShowData().rellenarComboBox("payment", "nombre", cmbMethod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBlue = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblSectionProd = new javax.swing.JLabel();
        fldAmount = new javax.swing.JTextField();
        lblSectionProd1 = new javax.swing.JLabel();
        fldDate = new javax.swing.JTextField();
        lblSectionProd2 = new javax.swing.JLabel();
        fldIDUser = new javax.swing.JTextField();
        lblSectionProd3 = new javax.swing.JLabel();
        fldIDClient = new javax.swing.JTextField();
        lblSectionProd4 = new javax.swing.JLabel();
        cmbMethod = new javax.swing.JComboBox<>();
        lblSectionProd5 = new javax.swing.JLabel();
        fldIDProd = new javax.swing.JTextField();
        lblSectionProd6 = new javax.swing.JLabel();
        fldPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fldBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1440, 650));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto Cn", 1, 48)); // NOI18N
        jLabel9.setText("VENTAS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 1090, 410));

        jPanelBlue.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 650));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 30));

        btnGuardar.setBackground(new java.awt.Color(102, 255, 51));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 170, 80));

        btnModificar.setBackground(new java.awt.Color(255, 255, 51));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Modificar");

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(31, 31, 31))
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 170, 80));

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 190, 100));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(23, 23, 23))
        );

        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 170, 80));

        lblSectionProd.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd.setText("Cantidad a vender:");
        getContentPane().add(lblSectionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, 260, 30));

        fldAmount.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAmountActionPerformed(evt);
            }
        });
        getContentPane().add(fldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, 270, 50));

        lblSectionProd1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd1.setText("Fecha:");
        getContentPane().add(lblSectionProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 120, 260, 30));

        fldDate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldDateActionPerformed(evt);
            }
        });
        getContentPane().add(fldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 150, 270, 50));

        lblSectionProd2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd2.setText("Id Usuario:");
        getContentPane().add(lblSectionProd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 370, 260, 30));

        fldIDUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldIDUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldIDUserActionPerformed(evt);
            }
        });
        getContentPane().add(fldIDUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 400, 270, 50));

        lblSectionProd3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd3.setText("Id Cliente:");
        getContentPane().add(lblSectionProd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 460, 260, 30));

        fldIDClient.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldIDClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldIDClientActionPerformed(evt);
            }
        });
        getContentPane().add(fldIDClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 490, 270, 50));

        lblSectionProd4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd4.setText("Forma de pago:");
        getContentPane().add(lblSectionProd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 550, 260, 30));

        cmbMethod.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        getContentPane().add(cmbMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 580, 270, 50));

        lblSectionProd5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd5.setText("Id producto:");
        getContentPane().add(lblSectionProd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 280, 260, 30));

        fldIDProd.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldIDProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldIDProdActionPerformed(evt);
            }
        });
        getContentPane().add(fldIDProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 310, 270, 50));

        lblSectionProd6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd6.setText("Precio:");
        getContentPane().add(lblSectionProd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 200, 260, 30));

        fldPrice.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldPriceActionPerformed(evt);
            }
        });
        getContentPane().add(fldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, 270, 50));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setText("Buscar por id de venta:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, -1, -1));

        fldBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldBuscarActionPerformed(evt);
            }
        });
        fldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fldBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(fldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 210, 30));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("BUSCAR");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if(fila == -1 ) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún dato");
        }
        else
        {
            id = jTable1.getValueAt(fila, 0).toString();
            String amount = (String)jTable1.getValueAt(fila, 1).toString();
            String price = (String)jTable1.getValueAt(fila, 2).toString();
            String date = (String)jTable1.getValueAt(fila, 3).toString();
            String idProd = (String)jTable1.getValueAt(fila, 4).toString();
            String idUser = (String)jTable1.getValueAt(fila, 5).toString();
            String idClient = (String)jTable1.getValueAt(fila, 6).toString();
            String payment = (String)jTable1.getValueAt(fila, 7).toString();

            fldAmount.setText(amount);
            fldPrice.setText(price);
            fldDate.setText(date);
            fldIDProd.setText(idProd);
            fldIDUser.setText(idUser);
            fldIDClient.setText(idClient);
            cmbMethod.setSelectedItem(payment);

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); //Guardar eje x y eje y
    }//GEN-LAST:event_headerMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        addCamps();

        int op = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos registrados?", "Confirme los datos registrados",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE); //preguntarle si quiere guardar
        if(op == 0)
        {
            InsertData.getInsertData().insertarDatos(nombreTabla, interrogaciones, column, nombreColumnas, campos); //insertar datos
            clear();
            showData();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        //Modificar datos

        addCamps();

        int op = JOptionPane.showConfirmDialog(null, "¿Desea modificar los datos?", "Confirme si desea modificar",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(op == 0){

            UpdateData.getUpdateData().actualizarDatos(nombreTabla, nombreColumnas, campos, "id", id);
            clear();
            showData();
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        Classes.ExecuteMenuOptions();
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        //Eliminar datos

        int op = JOptionPane.showConfirmDialog(null, "¿Desea eliminar los datos?", "Confirme si desea eliminar",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(op == 0)
        {
            DeleteData.getDeleteData().eliminarTablaCod(nombreTabla, "id", id);
            clear();
            showData();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void fldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldAmountActionPerformed

    private void fldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldDateActionPerformed

    private void fldIDUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldIDUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldIDUserActionPerformed

    private void fldIDClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldIDClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldIDClientActionPerformed

    private void fldIDProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldIDProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldIDProdActionPerformed

    private void fldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPriceActionPerformed

    private void fldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldBuscarActionPerformed

    }//GEN-LAST:event_fldBuscarActionPerformed

    private void fldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldBuscarKeyReleased
        if(fldBuscar.getText().trim().equals("")){
            showData();
        }
    }//GEN-LAST:event_fldBuscarKeyReleased

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        buscar = fldBuscar.getText();

        showData();
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSales().setVisible(true);
            }
        });
    }
    
         private void addCamps(){
          
        campos.add(fldAmount.getText());
        campos.add(fldPrice.getText());
        campos.add(fldDate.getText());
        campos.add(fldIDProd.getText());
        campos.add(fldIDUser.getText());
        campos.add(fldIDClient.getText());
        campos.add((String)cmbMethod.getSelectedItem());
        
    }
    
    private void clear(){
        fldAmount.setText(null);
        fldPrice.setText(null);
        fldDate.setText(null);
        fldIDProd.setText(null);
        fldIDUser.setText(null);
        fldIDClient.setText(null);
        cmbMethod.setSelectedItem(null);
    }
    
    private void showData() {
        ShowData.getShowData().mostrarDatos(nombreTabla, jTable1, 8, column, buscar, campoBuscar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JComboBox<String> cmbMethod;
    private javax.swing.JTextField fldAmount;
    private javax.swing.JTextField fldBuscar;
    private javax.swing.JTextField fldDate;
    private javax.swing.JTextField fldIDClient;
    private javax.swing.JTextField fldIDProd;
    private javax.swing.JTextField fldIDUser;
    private javax.swing.JTextField fldPrice;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSectionProd;
    private javax.swing.JLabel lblSectionProd1;
    private javax.swing.JLabel lblSectionProd2;
    private javax.swing.JLabel lblSectionProd3;
    private javax.swing.JLabel lblSectionProd4;
    private javax.swing.JLabel lblSectionProd5;
    private javax.swing.JLabel lblSectionProd6;
    // End of variables declaration//GEN-END:variables
}
