/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.DeleteData;
import Model.InsertData;
import Model.ShowData;
import Model.UpdateData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import Model.Classes;

public class FrmSectionProd extends javax.swing.JFrame {
    
    private int xMouse, yMouse;
    
    private List<String> nombreColumnas = new ArrayList<>();
    private List<String> interrogaciones = new ArrayList<>();
    
    private String nombreTabla = "section_prod";
    private List<String> column = new ArrayList<>();
    private List<String> campos = new ArrayList<>();
    private String id;
    
    private String buscar = "";
    private String campoBuscar = "nombre";
    
    
    public FrmSectionProd() {
        initComponents();
        
        column.add("Id");
        column.add("Nombre de la Sección del Producto");
        
        nombreColumnas.add("nombre");
        
        Model.AddImage.SetImageLabel(btnSalir, "src/images/atras.png");
        
        mostrarDatos();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnNuevo1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBlue = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblSectionProd = new javax.swing.JLabel();
        fldSectionProd = new javax.swing.JTextField();
        lblCodCatProd = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        BtnNuevo1.setText("Nuevo");

        jLabel5.setText("Categoría");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1442, 625));
        setMinimumSize(new java.awt.Dimension(1442, 625));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1442, 625));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto Cn", 1, 48)); // NOI18N
        jLabel9.setText("SECCIÓN DE PRODUCTOS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1090, 400));

        jPanelBlue.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 650));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 30));

        btnGuardar.setBackground(new java.awt.Color(102, 255, 51));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 170, 80));

        btnModificar.setBackground(new java.awt.Color(255, 255, 51));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Modificar");

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(31, 31, 31))
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 170, 80));

        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 190, 100));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(23, 23, 23))
        );

        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 170, 80));

        lblSectionProd.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblSectionProd.setText("Nombre de sección de producto:");
        getContentPane().add(lblSectionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 260, 30));

        fldSectionProd.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fldSectionProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSectionProdActionPerformed(evt);
            }
        });
        getContentPane().add(fldSectionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 220, 270, 50));

        lblCodCatProd.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCodCatProd.setText("Id seleccionado:");
        getContentPane().add(lblCodCatProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, -1, 40));

        txtId.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 90, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); //Guardar eje x y eje y
    }//GEN-LAST:event_headerMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        agregarCampos();

        int op = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos registrados?", "Confirme los datos registrados",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE); //preguntarle si quiere guardar
        if(op == 0)
        {
            InsertData.getInsertData().insertarDatos(nombreTabla, interrogaciones, column, nombreColumnas, campos); //insertar datos
            vaciarCampos();
            mostrarDatos();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        //Modificar datos
        
        agregarCampos();
        
        int op = JOptionPane.showConfirmDialog(null, "¿Desea modificar los datos?", "Confirme si desea modificar", 
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(op == 0){
            
            UpdateData.getUpdateData().actualizarDatos(nombreTabla, nombreColumnas, campos, "id", id);
            vaciarCampos();
            mostrarDatos();
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        Classes.ExecuteMenuOptions();
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        //Eliminar datos

        int op = JOptionPane.showConfirmDialog(null, "¿Desea eliminar los datos?", "Confirme si desea eliminar",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(op == 0)
        {
            DeleteData.getDeleteData().eliminarTablaCod(nombreTabla, "id", id);
            vaciarCampos();
            mostrarDatos();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void fldSectionProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSectionProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSectionProdActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if(fila == -1 ) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún dato");
        }
        else
        {
            id = jTable1.getValueAt(fila, 0).toString();
            String name = (String)jTable1.getValueAt(fila, 1).toString();
            
            txtId.setText(""+id);
            fldSectionProd.setText(name);
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSectionProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSectionProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSectionProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSectionProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSectionProd().setVisible(true);
            }
        });
    }
    
    private void agregarCampos(){
        campos.add(fldSectionProd.getText());
    }
    
    private void vaciarCampos(){
        fldSectionProd.setText(null);
        txtId.setText(null);
    }
    
    private void mostrarDatos() {
        ShowData.getShowData().mostrarDatos(nombreTabla, jTable1, 2, column, buscar, campoBuscar);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNuevo1;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JTextField fldSectionProd;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodCatProd;
    private javax.swing.JLabel lblSectionProd;
    private javax.swing.JLabel txtId;
    // End of variables declaration//GEN-END:variables
}
