/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author alumno
 */
public class FormaPagoForms extends javax.swing.JFrame {

    /**
     * Creates new form FormaPagoForms
     */
    public FormaPagoForms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblRegistro = new javax.swing.JLabel();
        jPanelBlue = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCod = new javax.swing.JLabel();
        fldCod = new javax.swing.JTextField();
        txtCod1 = new javax.swing.JLabel();
        fldCod1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(LblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(877, 12, 85, 37));

        jPanelBlue.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 650));

        jLabel5.setFont(new java.awt.Font("Roboto Cn", 1, 48)); // NOI18N
        jLabel5.setText("FORMAS DE PAGOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        txtCod.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtCod.setText("Nombre de forma de pago:");
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 440, -1));

        fldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldCodActionPerformed(evt);
            }
        });
        getContentPane().add(fldCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 620, 50));

        txtCod1.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txtCod1.setText("Codigo forma de pago:");
        getContentPane().add(txtCod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 320, -1));

        fldCod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldCod1ActionPerformed(evt);
            }
        });
        getContentPane().add(fldCod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 620, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldCodActionPerformed

    private void fldCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldCod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldCod1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPagoForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPagoForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPagoForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPagoForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPagoForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblRegistro;
    private javax.swing.JTextField fldCod;
    private javax.swing.JTextField fldCod1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JLabel txtCod;
    private javax.swing.JLabel txtCod1;
    // End of variables declaration//GEN-END:variables
}
