/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import logic.AddImage;

/**
 *
 * @author Esdras Abel Sapón Díaz
 */
public class FrmMenuOptions extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    /**
     * Creates new form test
     */
    public FrmMenuOptions() {
        initComponents();
        this.setLocationRelativeTo(this);
        AddImage.SetImageLabel(ImgFormain, "src/images/formain.png");
        AddImage.SetImageLabel(ImgClientes, "src/images/clientes.png");
        AddImage.SetImageLabel(ImgProveedores, "src/images/proveedores.png");
        AddImage.SetImageLabel(ImgProductos, "src/images/productos.png");
        AddImage.SetImageLabel(ImgMarcasProd, "src/images/marcas de productos.png");
        AddImage.SetImageLabel(ImgMedidasProd, "src/images/medidas de productos.png");
        AddImage.SetImageLabel(ImgFormasPago, "src/images/metodos de pago.png");
        AddImage.SetImageLabel(ImgFamiliaProd, "src/images/familias de productos.png");
        AddImage.SetImageLabel(ImgSeccionesProd, "src/images/secciones de productos.png");
        AddImage.SetImageLabel(ImgUsuariosDR, "src/images/usuarios con derechos y restricciones.png");
        AddImage.SetImageLabel(ImgSalir, "src/images/salir.png");
        AddImage.SetImageLabel(ImgListado, "src/images/listado.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        ImgFormain = new javax.swing.JLabel();
        ImgClientes = new javax.swing.JLabel();
        PnlClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ImgProveedores = new javax.swing.JLabel();
        PnlProveedores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ImgProductos = new javax.swing.JLabel();
        PnlProductos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ImgMarcasProd = new javax.swing.JLabel();
        PnlMarcasProd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ImgMedidasProd = new javax.swing.JLabel();
        PnlMedidasProd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ImgFormasPago = new javax.swing.JLabel();
        PnlFormasPago = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ImgFamiliaProd = new javax.swing.JLabel();
        PnlFamiliaProd = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ImgSeccionesProd = new javax.swing.JLabel();
        PnlSeccionesProd = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ImgUsuariosDR = new javax.swing.JLabel();
        PnlUsuariosDR = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ImgSalir = new javax.swing.JLabel();
        PnlSalir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        ImgListado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(960, 644));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 644));

        lblMenu.setFont(new java.awt.Font("Roboto Cn", 1, 48)); // NOI18N
        lblMenu.setText("MENÚ DE OPCIONES");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        getContentPane().add(ImgFormain, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 220, 100));
        getContentPane().add(ImgClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, 80));

        PnlClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout PnlClientesLayout = new javax.swing.GroupLayout(PnlClientes);
        PnlClientes.setLayout(PnlClientesLayout);
        PnlClientesLayout.setHorizontalGroup(
            PnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlClientesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        PnlClientesLayout.setVerticalGroup(
            PnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlClientesLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 60));
        getContentPane().add(ImgProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, 80));

        PnlProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Proveedores");

        javax.swing.GroupLayout PnlProveedoresLayout = new javax.swing.GroupLayout(PnlProveedores);
        PnlProveedores.setLayout(PnlProveedoresLayout);
        PnlProveedoresLayout.setHorizontalGroup(
            PnlProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlProveedoresLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        PnlProveedoresLayout.setVerticalGroup(
            PnlProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlProveedoresLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 60));
        getContentPane().add(ImgProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 80, 80));

        PnlProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Productos");

        javax.swing.GroupLayout PnlProductosLayout = new javax.swing.GroupLayout(PnlProductos);
        PnlProductos.setLayout(PnlProductosLayout);
        PnlProductosLayout.setHorizontalGroup(
            PnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlProductosLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        PnlProductosLayout.setVerticalGroup(
            PnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlProductosLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 60));
        getContentPane().add(ImgMarcasProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 80, 80));

        PnlMarcasProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Marcas de Productos");

        javax.swing.GroupLayout PnlMarcasProdLayout = new javax.swing.GroupLayout(PnlMarcasProd);
        PnlMarcasProd.setLayout(PnlMarcasProdLayout);
        PnlMarcasProdLayout.setHorizontalGroup(
            PnlMarcasProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMarcasProdLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        PnlMarcasProdLayout.setVerticalGroup(
            PnlMarcasProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMarcasProdLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlMarcasProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 240, 60));
        getContentPane().add(ImgMedidasProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 90, 90));

        PnlMedidasProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setText("Medidas de Productos");

        javax.swing.GroupLayout PnlMedidasProdLayout = new javax.swing.GroupLayout(PnlMedidasProd);
        PnlMedidasProd.setLayout(PnlMedidasProdLayout);
        PnlMedidasProdLayout.setHorizontalGroup(
            PnlMedidasProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMedidasProdLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        PnlMedidasProdLayout.setVerticalGroup(
            PnlMedidasProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMedidasProdLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlMedidasProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 250, 60));
        getContentPane().add(ImgFormasPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 80, 80));

        PnlFormasPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("Formas de Pago");

        javax.swing.GroupLayout PnlFormasPagoLayout = new javax.swing.GroupLayout(PnlFormasPago);
        PnlFormasPago.setLayout(PnlFormasPagoLayout);
        PnlFormasPagoLayout.setHorizontalGroup(
            PnlFormasPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFormasPagoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        PnlFormasPagoLayout.setVerticalGroup(
            PnlFormasPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFormasPagoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlFormasPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 190, 60));
        getContentPane().add(ImgFamiliaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 80, 80));

        PnlFamiliaProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlFamiliaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlFamiliaProdMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setText("Categorías/Familias Productos");

        javax.swing.GroupLayout PnlFamiliaProdLayout = new javax.swing.GroupLayout(PnlFamiliaProd);
        PnlFamiliaProd.setLayout(PnlFamiliaProdLayout);
        PnlFamiliaProdLayout.setHorizontalGroup(
            PnlFamiliaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFamiliaProdLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        PnlFamiliaProdLayout.setVerticalGroup(
            PnlFamiliaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFamiliaProdLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlFamiliaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 350, 60));
        getContentPane().add(ImgSeccionesProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 80, 80));

        PnlSeccionesProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setText("Secciones de Productos");

        javax.swing.GroupLayout PnlSeccionesProdLayout = new javax.swing.GroupLayout(PnlSeccionesProd);
        PnlSeccionesProd.setLayout(PnlSeccionesProdLayout);
        PnlSeccionesProdLayout.setHorizontalGroup(
            PnlSeccionesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSeccionesProdLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        PnlSeccionesProdLayout.setVerticalGroup(
            PnlSeccionesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSeccionesProdLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlSeccionesProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 270, 60));
        getContentPane().add(ImgUsuariosDR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 100, 80));

        PnlUsuariosDR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlUsuariosDR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlUsuariosDRMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setText("Usuarios con derechos y restricciones");

        javax.swing.GroupLayout PnlUsuariosDRLayout = new javax.swing.GroupLayout(PnlUsuariosDR);
        PnlUsuariosDR.setLayout(PnlUsuariosDRLayout);
        PnlUsuariosDRLayout.setHorizontalGroup(
            PnlUsuariosDRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlUsuariosDRLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        PnlUsuariosDRLayout.setVerticalGroup(
            PnlUsuariosDRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUsuariosDRLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlUsuariosDR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 420, 60));
        getContentPane().add(ImgSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 70, 70));

        PnlSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlSalirMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setText("Salir");

        javax.swing.GroupLayout PnlSalirLayout = new javax.swing.GroupLayout(PnlSalir);
        PnlSalir.setLayout(PnlSalirLayout);
        PnlSalirLayout.setHorizontalGroup(
            PnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSalirLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        PnlSalirLayout.setVerticalGroup(
            PnlSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSalirLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        getContentPane().add(PnlSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 70, 60));

        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));
        getContentPane().add(ImgListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlSalirMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_PnlSalirMouseClicked

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY(); //Guardar eje x y eje y       
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse); //codigo para poder mover la ventana del programa        // TODO add your handling code here:
    }//GEN-LAST:event_HeaderMouseDragged

    private void PnlUsuariosDRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlUsuariosDRMouseClicked
        logic.Classes.ExecuteUsers();
    }//GEN-LAST:event_PnlUsuariosDRMouseClicked

    private void PnlFamiliaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlFamiliaProdMouseClicked
        logic.Classes.ExecuteCatProd();
        this.dispose();
    }//GEN-LAST:event_PnlFamiliaProdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel ImgClientes;
    private javax.swing.JLabel ImgFamiliaProd;
    private javax.swing.JLabel ImgFormain;
    private javax.swing.JLabel ImgFormasPago;
    private javax.swing.JLabel ImgListado;
    private javax.swing.JLabel ImgMarcasProd;
    private javax.swing.JLabel ImgMedidasProd;
    private javax.swing.JLabel ImgProductos;
    private javax.swing.JLabel ImgProveedores;
    private javax.swing.JLabel ImgSalir;
    private javax.swing.JLabel ImgSeccionesProd;
    private javax.swing.JLabel ImgUsuariosDR;
    private javax.swing.JPanel PnlClientes;
    private javax.swing.JPanel PnlFamiliaProd;
    private javax.swing.JPanel PnlFormasPago;
    private javax.swing.JPanel PnlMarcasProd;
    private javax.swing.JPanel PnlMedidasProd;
    private javax.swing.JPanel PnlProductos;
    private javax.swing.JPanel PnlProveedores;
    private javax.swing.JPanel PnlSalir;
    private javax.swing.JPanel PnlSeccionesProd;
    private javax.swing.JPanel PnlUsuariosDR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
